name: Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run static checks
        run: make check
